name: ci

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Run integration tests
        run: |
          pip install -e .
          pip install pytest
          pip install dialogue-tester
          python3 -m pytest -k examples_test
  # container:
  #   needs: [tests]
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v2
  #     - name: Build the Docker image
  #       run: docker build . --file Dockerfile --tag vcwild/lisp-interpreter:latest
